-- Diff-first 拒绝是用户决策后的 Task 终态，Workspace 修改保留且不进入交付。
ALTER TABLE tasks
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PLANNING'
        COMMENT 'PLANNING/PENDING/RUNNING/WAITING_DIFF_CONFIRMATION/DIFF_REJECTED/DELIVERING/SUCCEEDED/DELIVERY_FAILED/FAILED/CANCELLING/CANCELLED';
