-- 交付事实拆分：PUSHED 表示 Worker 已核验远端 feature branch；WAITING_PREFLIGHT 表示
-- MR 前 Dry Run 与独立 CQ+1 尚未完成，不得被标记为 DELIVERY_FAILED。
-- 列为 VARCHAR，修改仅固化枚举语义与默认建表脚本保持一致，不重写任何存量状态。

ALTER TABLE tasks
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PLANNING'
    COMMENT 'PLANNING/PENDING/RUNNING/WAITING_DIFF_CONFIRMATION/WAITING_PREFLIGHT/DIFF_REJECTED/DELIVERING/SUCCEEDED/DELIVERY_FAILED/FAILED/CANCELLING/CANCELLED';

ALTER TABLE diffs
    MODIFY COLUMN delivery_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED'
    COMMENT '交付状态：NOT_STARTED/COMMITTED/PUSHED/MR_CREATED/FAILED';
